server:
    context-path: /
    port: 8081
spring:
  data:
    elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: localhost:9300
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/aa?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123
        driverClassName: com.mysql.jdbc.Driver
mybatis:
    config-location: classpath:mybatis-config.xml